### ISSUE TITLE
Vendor Gin conflict

### ISSUE THREAD

**Issue by MimmDev** [appleboy/gin-jwt#120]
Not sure why this exactly this is being caused, but it occurs since the commit "feat: add vendor to git tree".

`cannot use c (type *"github.com/gin-gonic/gin".Context) as type *"github.com/appleboy/gin-jwt/vendor/github.com/gin-gonic/gin".Context in argument to "github.com/appleboy/gin-jwt".ExtractClaims`

**Comment by appleboy** [comment]
@MimmDev I can't reproduce this problem. Can you show me the detail information or some example code?

**Comment by MimmDev** [comment]
Hi @appleboy, thanks for the quick reply!

The issue occurs when using jwt.ExtractClaims(c), where c is of type *gin.Context, used in my own package. To my knowledge, it happens because my package imports "github.com/gin-gonic/gin" and gin-jwt imports gin from its vendor folder, which technically means there are two types of *gin.Context (they are actually identical, but since they come from different file locations Go considers them to be incompatible).

**Comment by appleboy** [comment]
any updates?

**Comment by tcr-ableton** [comment]
Hi, I'm running into the exact same problem since today. Everything was building perfectly fine on my last build friday :-)

I build the code inside a container with the `--no-cache` option. And my code basically looks like the example:
```go
import (
	"github.com/gin-gonic/gin"
	"github.com/appleboy/gin-jwt"	
)

func main() {
authMiddleware := &jwt.GinJWTMiddleware{
		Realm:      "here",
		Key:        []byte("bla"),
		Timeout:    24 * time.Hour * 30,
		MaxRefresh: time.Hour,
		Authenticator: func(username string, password string, c *gin.Context) (string, bool) {},
		Unauthorized: func(c *gin.Context, code int, message string) {},
		TokenLookup:   "header:Authorization",
		TokenHeadName: "Bearer",
		TimeFunc:      time.Now,
	}
}
```

Any pointers on how to solve this?

**Comment by appleboy** [comment]
@tcr-ableton 

find:

```go
Authenticator: func(username string, password string, c *gin.Context) (string, bool) {},
```

replace:

```go
Authenticator: func(username string, password string, c *gin.Context) (interface{}, bool) {},
```

**Comment by tcr-ableton** [comment]
I've found out your friday's commit modifying the API in the meantime, and did the change you suggested. My current `Authenticator` looks like this now:
```go
Authenticator: func(username string, password string, c *gin.Context) (interface{}, bool) {}
```

and gets the previously mentioned error about vendoring:
```bash
# _/Users/tcr/Dev/Ableton/Content/nestor/sync
./main.go:93: cannot use func literal (type func(string, string, *"github.com/gin-gonic/gin".Context) (interface {}, bool)) as type func(string, string, *"github.com/appleboy/gin-jwt/vendor/github.com/gin-gonic/gin".Context) (interface {}, bool) in field value
```

For reference, I made sure to start from a clean `GOPATH` :-)

**Comment by appleboy** [comment]
Could you also help to try this example: 

https://github.com/appleboy/gin-jwt/blob/abd83166c85e5251921dd1c76d6355c94fbd79ff/example/server.go#L1-L98

It is working for me with latest gin-jwt and gin framework version.

**Comment by appleboy** [comment]
@MimmDev @tcr-ableton I found the issue. I will remove the vendor folder.

**Comment by tcr-ableton** [comment]
I pasted your code into a `main.go` and `go build main.go` and get these errors (which look quite the same as before, just applied to a different piece of code):
```bash
# command-line-arguments
./main.go:14:30: cannot use c (type *"github.com/gin-gonic/gin".Context) as type *"github.com/appleboy/gin-jwt/vendor/github.com/gin-gonic/gin".Context in argument to "github.com/appleboy/gin-jwt".ExtractClaims
./main.go:44:17: cannot use func literal (type func(string, string, *"github.com/gin-gonic/gin".Context) (interface {}, bool)) as type func(string, string, *"github.com/appleboy/gin-jwt/vendor/github.com/gin-gonic/gin".Context) (interface {}, bool) in field value
./main.go:55:16: cannot use func literal (type func(interface {}, *"github.com/gin-gonic/gin".Context) bool) as type func(interface {}, *"github.com/appleboy/gin-jwt/vendor/github.com/gin-gonic/gin".Context) bool in field value
./main.go:62:16: cannot use func literal (type func(*"github.com/gin-gonic/gin".Context, int, string)) as type func(*"github.com/appleboy/gin-jwt/vendor/github.com/gin-gonic/gin".Context, int, string) in field value
./main.go:86:34: cannot use authMiddleware.LoginHandler (type func(*"github.com/appleboy/gin-jwt/vendor/github.com/gin-gonic/gin".Context)) as type "github.com/gin-gonic/gin".HandlerFunc in argument to r.RouterGroup.POST
./main.go:89:41: cannot use authMiddleware.MiddlewareFunc() (type "github.com/appleboy/gin-jwt/vendor/github.com/gin-gonic/gin".HandlerFunc) as type "github.com/gin-gonic/gin".HandlerFunc in argument to auth.Use
./main.go:92:45: cannot use authMiddleware.RefreshHandler (type func(*"github.com/appleboy/gin-jwt/vendor/github.com/gin-gonic/gin".Context)) as type "github.com/gin-gonic/gin".HandlerFunc in argument to auth.GET
```

I have tried with both go 1.8 and go 1.10.2 and same result :-)

**Comment by tcr-ableton** [comment]
Great news! Thanks a lot for helping us out on this 👍

**Comment by appleboy** [comment]
@tcr-ableton @MimmDev fixed in #124 Please try it out.

**Comment by tcr-ableton** [comment]
It is indeed fixed thanks! 👍

**Comment by andofcourse** [comment]
I'm still getting this issue - I'm using the example code:
```
	authMiddleware := &jwt.GinJWTMiddleware{
		Realm:      "test zone",
		Key:        []byte("secret key"),
		Timeout:    time.Hour,
		MaxRefresh: time.Hour,
		Authenticator: func(userId string, password string, c *gin.Context) (interface{}, bool) {
			if (userId == "admin" && password == "admin") || (userId == "test" && password == "test") {
				return &User{
					UserName:  userId,
					LastName:  "Bo-Yi",
					FirstName: "Wu",
				}, true
			}

			return nil, false
		},
```

and getting `cannot use func literal (type func(string, string, *gin.Context) (interface {}, bool)) as type func(string, string, *gin.Context) (string, bool) in field value`. 

I'm not entirely sure where this is coming from - I've checked my vendor file and all that's inside of gin-jwt folder is auth_jwt.go, the makefile, readme and license, so clearly #124 is being included. I've got a fresh GOPATH with nothing in it as well. 

Any suggestions?

**Comment by jimfilippou** [comment]
I am still facing this issue...

**Comment by appleboy** [comment]
@andofcourse @jimfilippou what is your vendor tool?
